# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49f2f3bea5e745bb2838643bb1f2b1da2a44d6956a70589212c1e59781867fe0597375a5ea1d9b26a01a2bc25b19ebf84e4efe712c5c50ec85425262eed4cfb7

test:
  secret_key_base: 981dc7a62da3762e4801eff88a5ec23f9308c716c9684719ec8b80fda9cada71f686af4e19a96067d5329e3ee9308fd44421c1163a36ccd329834d7d42ada793

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
